### ISSUE TITLE
`with_wrapper` does not support `mock_constructor`

### ISSUE THREAD

**Issue by xsh6528** [facebookincubator/TestSlide#15]
```
from testslide.dsl import context


class MyClass(object):
    __slots__ = ["value"]

    def __init__(self, value):
        self.value = value


@context  # noqa
def mock_constructor_with_wrapper_test(context):

    @context.sub_context
    def intercept_context(context):
        @context.before
        def intercept_call_to_constructer(self):
            def wrapper(original_callable, *args, **kwargs):
                obj = original_callable(*args, **kwargs)
                obj.value += 1
                return obj

            self.mock_constructor(
                __name__, "MyClass"
            ).with_wrapper(wrapper).and_assert_called_once()

        @context.example
        def call_constructor(self):
            obj = MyClass(value=1)
            self.assertEqual(obj.value, 2)

    @context.example
    def call_constructor(self):
        obj = MyClass(value=1)
        self.assertEqual(obj.value, 1)

```

Error

```
Failures:

  0) mock constructor with wrapper test, intercept context: call constructor
    1) TypeError: original_callable() takes at least 1 argument (0 given)
      File "experimental/shihaoxu/testslide/mock_constructor_with_wrapper_test.py", line 31, in call_constructor
        obj = MyClass(value=1)
      File "experimental/shihaoxu/testslide/mock_constructor_with_wrapper_test.py", line 21, in wrapper
        obj = original_callable(*args, **kwargs)
```

**Comment by fornellas** [comment]
It seems the issue is [here](https://github.com/facebookincubator/TestSlide/blob/master/testslide/mock_constructor.py#L85): the `_` should likely be dropped.

How do you feel about doing a PR for this, also add your awesome test case to reproduce the issue [here](https://github.com/facebookincubator/TestSlide/blob/master/tests/mock_constructor_testslide.py)?

**Comment by danielkza** [comment]
Looking a bit more into this, it seems simply dropping the `_` in the callback is not sufficient. In my understanding the problem is rooted in the nature of `mock_constructor`: while the intended use case is to configure it as a constructor call (that *does not* take the class as the first argument), in practice it is setup as a mock of the `__new__` method (which *does* take the constructed class as the first argument). If we do the simple fix we can fix one usage but we break the other.

To deal with that "duality", adding a new subclass of `_MockCallableDSL` that properly deals with the argument seems like a good approach. That can substitute the `prepend_first_arg` machinery in a less error-prone way.

**Comment by fornellas** [comment]
https://github.com/facebookincubator/TestSlide/pull/32 should fix this.

**Comment by danielkza** [comment]
I tried a different approach in the linked PR, tell if it you think it's worth the trouble.
