### ISSUE TITLE
Support for async functions with mock_callable()

### ISSUE THREAD

**Issue by fornellas** [facebookincubator/TestSlide#19]
Support for [async functions](https://docs.python.org/3/library/asyncio.html) with `mock_callable()`.

Here's a [half working patch](https://github.com/fornellas/TestSlide/commit/e157bbf06c4ff0c6ed9264f00e3610665c395196) for that, as a starting point.

To prove that any solution works, all relevant tests at `tests/mock_callable_testslide.py` must be updated to to cover async cases (eg: async function at module, async instance method, async class method etc).

PS: previous PR https://github.com/facebookincubator/TestSlide/pull/8

**Comment by david-caro** [comment]
Hi @fornellas, I have a question about this, in order to support asyncio, the whole module would have to drop python2 support right?

**Comment by fornellas** [comment]
I suppose you're correct. Python 2 is dying anyway, it's support can be dropped at this point.

**Comment by fornellas** [comment]
PS: I created a milestone for async stuff https://github.com/facebookincubator/TestSlide/milestone/1, as there's more stuff to implement.

**Comment by jivid** [comment]
I've put up #60 to provide `mock_async_callable`. I do believe having an explicit `mock_async_callable` is better than having the `mock_callable` interface detect whether it's received a coroutine or a regular function. The latter just feels like it would hide too much from the users.

**Comment by fried** [comment]
unittest.IsolatedAsyncioTestCase in 3.8 uses that.  So to have async test methods they have to explicitly be coroutines.  No sync methods that return awaitables, since that's pretty hairy. 
Also the AsyncMock in 3.8 is also a really good interface for async mocks, in that it looks at the spec and if its a coroutine the mocks that return when that is called is another AsyncMock,  otherwise you get a normal MagicMock.
